name: request attendance

on:
  workflow_dispatch:
  schedule:
    # - cron: "55,25 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21 * * 1,2,3,4,5,6"
    # convert UTC to KST
    - cron: "53,24 22,23,0,1,2,3,4,5,6,7,8,9,10,11,12 * * *"

jobs:
  attendance-request:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Seoul"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Code
        run: |
          python main.py
